### ISSUE TITLE
Recipe app

### ISSUE THREAD

**Issue by Elhambasir** [Elhambasir/recepies-app#14]
### Group members in this project are:

- Person A : @Bennyjoez 
- Person B : @Elhambasir

Link to the [Kanban Board](https://github.com/Elhambasir/recepies-app/projects/1).
Thank you for reviewing.

**Comment by bobb-Rob** [comment]
## STATUS: CHANGES REQUIRED ♻️
Hi @Elhambasir and @Bennyjoez , 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you are almost there!  😃 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

## Highlights
✅ The correct workflow is used. 
✅ Your work is well documented.

## Required Changes ♻️
_Check the comments under the review._

Some Kanban cards are without time estimation. Kindly fix this, even though there are group tasks, you still need to add time estimation. 
<img width="263" alt="image" src="https://github.com/Elhambasir/recepies-app/assets/84156714/c350eb7f-0a93-4896-97fb-782dad20eb91">



Cheers and Happy coding!👏👏👏

**Comment by iambenkis** [comment]
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

✅ The correct workflow is used.
✅ Your work is well documented.

Your project is complete!  There is nothing else to say other than... it's time to START  it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @iambenkis in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
